In [1]:
import csv
import json
import pandas as pd
from datetime import datetime
import numpy as np

mainfolder = "../data_2019_processed/"
file_name_modifier = "_smote"
outputFolders = ""

In [2]:
# take the list of directories and concat them
def loadDataFromFolders(foldersToLoad,inputFolders,fileType = ""):
    print(len(foldersToLoad), "datasets")
    for i in range(0,len(foldersToLoad)):
        currentFolder = foldersToLoad[i]
        print(i , "-", currentFolder,inputFolders+"student_"+currentFolder+"_transformed"+fileType+".csv")
        #print(trainingDataSet[i])
        if(i == 0):
            temp_data = pd.read_csv(inputFolders+"student_"+currentFolder+"_transformed"+fileType+".csv")
        else:
            dataset = pd.read_csv(inputFolders+"student_"+currentFolder+"_transformed"+fileType+".csv")
            temp_data = pd.concat([temp_data, dataset])
    # return the dataset        
    return temp_data

In [3]:
# client datasets used on the training process (75% of data)
trainFolders =  ['0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs',
                '0tdmm6rwW3KquQ73ATYYJ5JkpMtvbppJ0VzA2GExdA', 
                '2cyV53lVyUtlMj0BRwilEWtYJwUiviYoL48cZBPBq0', 
                '2J22RukYnEbKTk7t+iUVDBkorcyL5NKN6TrLe89ys', 
                #['5FLZBTVAPwdq9QezHE2sVCJIs7p+r6mCemA2gp9jATk'], #does not have the file
                '7EYF5I04EVqisUJCVNHlqn77UAuOmwL2Dahxd3cA', 
                'a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4', 
                'ae4JJBZDycEcY8McJF+3BxyvZ1619y03BNdCxzpZTc', 
                'Ch3u5Oaz96VSrQbf0z31X6jEIbeIekkC0mwPzCdeJ1U', 
                'CH8f0yZkZL13zWuE9ks1CkVJRVrr+jsGdUXHrZ6YeA', 
                'DHO1K4jgiwZJOfQTrxvKE2vn7hkjamigroGD5IaeRc', 
                #'DHPqzSqSttiba1L3BD1cptNJPjSxZ8rXxF9mY3za6WA', # does not have asleep data
                'dQEFscjqnIlug8Tgq97JohhSQPG2DEOWJqS86wCrcY', 
                'HFvs2CohmhHte+AaCzFasjzegGzxZKPhkrX23iI6Xo', 
                'jgB9E8v3Z6PKdTRTCMAijBllA9YEMtrmHbe4qsbmJWw', 
                'JkY++R7E8myldLN3on6iQ78Ee78zCbrLuggfwGju3I', 
                'K4SLohf+TN1Ak8Dn8iE3Lme7rEMPISfppB2sXfHX8', 
                'oGaWetJJJEWHuvYdWYo826SQxfhCExVVQ2da8LE1Y7Q', 
                'pyt24oiDAHsmgWMvkFKz2fn2pwcHiXchd6KchLM', 
                #'PZCf1nfvhR+6fk+7+sPNMYOgb8BAMmtQtfoRS83Suc', # does not have asleep data
                'QUNCATForxzK0HHw46LrGOMWh0eVA8Y5XWEiUXX+cQ', 
                #'rIl2UK9+bQ+tzpFdbJAdbBxEa5GbgrgC030yEaENLw', 
                #'RoBW3cDOO9wWRMPO2twQff83MPc+OXn6gJ+a1DafreI', 
                'SH3kQeyd5volraxw8vOyhlowNqWBPr1IJ9URNXUL4']
                #'VVpwFNMrEglveh6MDN8lrRzTy5OwzglD4FURfM4A2is', 
                #'Wa1mcNmbh66S7VS6GIzyfCFMD3SGhbtDQyFP1ywJEsw', 
                #'XCKRE0BWRHxfP1kZIihgtT+jUjSp2GE8v5ZlhcIhVmA', 
                #'YI5Y79K6GXqAUoGP6PNyII8WKlAoel4urDxWSVVOvBw', 
                #'ypklj+8GJ15rOIH1lpKQtFJOuK+VdvyCuBPqhY3aoM', 
                #'ZSsAZ0Pq+MCqFrnjsRFn5Ua09pMCVaOV9c8ZuYb7XQY']
            
# client datasets used on the training process (25% of data)
testFolders =  [#'0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs',
                #'0tdmm6rwW3KquQ73ATYYJ5JkpMtvbppJ0VzA2GExdA', 
                #'2cyV53lVyUtlMj0BRwilEWtYJwUiviYoL48cZBPBq0', 
                #'2J22RukYnEbKTk7t+iUVDBkorcyL5NKN6TrLe89ys', 
                #['5FLZBTVAPwdq9QezHE2sVCJIs7p+r6mCemA2gp9jATk'], #does not have the file
                #'7EYF5I04EVqisUJCVNHlqn77UAuOmwL2Dahxd3cA', 
                #'a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4', 
                #'ae4JJBZDycEcY8McJF+3BxyvZ1619y03BNdCxzpZTc', 
                #'Ch3u5Oaz96VSrQbf0z31X6jEIbeIekkC0mwPzCdeJ1U', 
                #'CH8f0yZkZL13zWuE9ks1CkVJRVrr+jsGdUXHrZ6YeA', 
                #'DHO1K4jgiwZJOfQTrxvKE2vn7hkjamigroGD5IaeRc', 
                #'DHPqzSqSttiba1L3BD1cptNJPjSxZ8rXxF9mY3za6WA', # does not have asleep data
                #'dQEFscjqnIlug8Tgq97JohhSQPG2DEOWJqS86wCrcY', 
                #'HFvs2CohmhHte+AaCzFasjzegGzxZKPhkrX23iI6Xo', 
                #'jgB9E8v3Z6PKdTRTCMAijBllA9YEMtrmHbe4qsbmJWw', 
                #'JkY++R7E8myldLN3on6iQ78Ee78zCbrLuggfwGju3I', 
                #'K4SLohf+TN1Ak8Dn8iE3Lme7rEMPISfppB2sXfHX8', 
                #'oGaWetJJJEWHuvYdWYo826SQxfhCExVVQ2da8LE1Y7Q', 
                #'pyt24oiDAHsmgWMvkFKz2fn2pwcHiXchd6KchLM', 
                #'PZCf1nfvhR+6fk+7+sPNMYOgb8BAMmtQtfoRS83Suc', # does not have asleep data
                #'QUNCATForxzK0HHw46LrGOMWh0eVA8Y5XWEiUXX+cQ', 
                'rIl2UK9+bQ+tzpFdbJAdbBxEa5GbgrgC030yEaENLw', 
                'RoBW3cDOO9wWRMPO2twQff83MPc+OXn6gJ+a1DafreI', 
                #'SH3kQeyd5volraxw8vOyhlowNqWBPr1IJ9URNXUL4'] 
                'VVpwFNMrEglveh6MDN8lrRzTy5OwzglD4FURfM4A2is', 
                'Wa1mcNmbh66S7VS6GIzyfCFMD3SGhbtDQyFP1ywJEsw', 
                'XCKRE0BWRHxfP1kZIihgtT+jUjSp2GE8v5ZlhcIhVmA', 
                'YI5Y79K6GXqAUoGP6PNyII8WKlAoel4urDxWSVVOvBw', 
                'ypklj+8GJ15rOIH1lpKQtFJOuK+VdvyCuBPqhY3aoM', 
                'ZSsAZ0Pq+MCqFrnjsRFn5Ua09pMCVaOV9c8ZuYb7XQY']

# client datasets used on the training process (75% of data)
allFolders =  ['0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs',
                '0tdmm6rwW3KquQ73ATYYJ5JkpMtvbppJ0VzA2GExdA', 
                '2cyV53lVyUtlMj0BRwilEWtYJwUiviYoL48cZBPBq0', 
                '2J22RukYnEbKTk7t+iUVDBkorcyL5NKN6TrLe89ys', 
                #['5FLZBTVAPwdq9QezHE2sVCJIs7p+r6mCemA2gp9jATk'], #does not have the file
                '7EYF5I04EVqisUJCVNHlqn77UAuOmwL2Dahxd3cA', 
                'a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4', 
                'ae4JJBZDycEcY8McJF+3BxyvZ1619y03BNdCxzpZTc', 
                'Ch3u5Oaz96VSrQbf0z31X6jEIbeIekkC0mwPzCdeJ1U', 
                'CH8f0yZkZL13zWuE9ks1CkVJRVrr+jsGdUXHrZ6YeA', 
                'DHO1K4jgiwZJOfQTrxvKE2vn7hkjamigroGD5IaeRc', 
                #'DHPqzSqSttiba1L3BD1cptNJPjSxZ8rXxF9mY3za6WA', # does not have asleep data
                'dQEFscjqnIlug8Tgq97JohhSQPG2DEOWJqS86wCrcY', 
                'HFvs2CohmhHte+AaCzFasjzegGzxZKPhkrX23iI6Xo', 
                'jgB9E8v3Z6PKdTRTCMAijBllA9YEMtrmHbe4qsbmJWw', 
                'JkY++R7E8myldLN3on6iQ78Ee78zCbrLuggfwGju3I', 
                'K4SLohf+TN1Ak8Dn8iE3Lme7rEMPISfppB2sXfHX8', 
                'oGaWetJJJEWHuvYdWYo826SQxfhCExVVQ2da8LE1Y7Q', 
                'pyt24oiDAHsmgWMvkFKz2fn2pwcHiXchd6KchLM', 
                #'PZCf1nfvhR+6fk+7+sPNMYOgb8BAMmtQtfoRS83Suc', # does not have asleep data
                'QUNCATForxzK0HHw46LrGOMWh0eVA8Y5XWEiUXX+cQ', 
                'rIl2UK9+bQ+tzpFdbJAdbBxEa5GbgrgC030yEaENLw', 
                'RoBW3cDOO9wWRMPO2twQff83MPc+OXn6gJ+a1DafreI', 
                'SH3kQeyd5volraxw8vOyhlowNqWBPr1IJ9URNXUL4',
                'VVpwFNMrEglveh6MDN8lrRzTy5OwzglD4FURfM4A2is', 
                'Wa1mcNmbh66S7VS6GIzyfCFMD3SGhbtDQyFP1ywJEsw', 
                'XCKRE0BWRHxfP1kZIihgtT+jUjSp2GE8v5ZlhcIhVmA', 
                'YI5Y79K6GXqAUoGP6PNyII8WKlAoel4urDxWSVVOvBw', 
                'ypklj+8GJ15rOIH1lpKQtFJOuK+VdvyCuBPqhY3aoM', 
                'ZSsAZ0Pq+MCqFrnjsRFn5Ua09pMCVaOV9c8ZuYb7XQY']

# All data correlation

In [4]:
dataframe = loadDataFromFolders(allFolders,mainfolder,file_name_modifier)
#dataframe = pd.read_csv("dados2019/student_a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4.csv", delimiter=',', encoding="utf8")

27 datasets
0 - 0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs ../data_2019_processed/student_0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs_transformed_smote.csv
1 - 0tdmm6rwW3KquQ73ATYYJ5JkpMtvbppJ0VzA2GExdA ../data_2019_processed/student_0tdmm6rwW3KquQ73ATYYJ5JkpMtvbppJ0VzA2GExdA_transformed_smote.csv
2 - 2cyV53lVyUtlMj0BRwilEWtYJwUiviYoL48cZBPBq0 ../data_2019_processed/student_2cyV53lVyUtlMj0BRwilEWtYJwUiviYoL48cZBPBq0_transformed_smote.csv
3 - 2J22RukYnEbKTk7t+iUVDBkorcyL5NKN6TrLe89ys ../data_2019_processed/student_2J22RukYnEbKTk7t+iUVDBkorcyL5NKN6TrLe89ys_transformed_smote.csv
4 - 7EYF5I04EVqisUJCVNHlqn77UAuOmwL2Dahxd3cA ../data_2019_processed/student_7EYF5I04EVqisUJCVNHlqn77UAuOmwL2Dahxd3cA_transformed_smote.csv
5 - a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4 ../data_2019_processed/student_a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4_transformed_smote.csv
6 - ae4JJBZDycEcY8McJF+3BxyvZ1619y03BNdCxzpZTc ../data_2019_processed/student_ae4JJBZDycEcY8McJF+3BxyvZ1619y03BNdCxzpZTc_transformed_smote.csv
7 - Ch3u5Oaz96VSrQbf0z31X6jEIbeIekkC0mwPzCdeJ1U ../data_2019_processed/student_Ch3u5Oaz96VSrQbf0z31X6jEIbeIekkC0mwPzCdeJ1U_transformed_smote.csv
8 - CH8f0yZkZL13zWuE9ks1CkVJRVrr+jsGdUXHrZ6YeA ../data_2019_processed/student_CH8f0yZkZL13zWuE9ks1CkVJRVrr+jsGdUXHrZ6YeA_transformed_smote.csv
9 - DHO1K4jgiwZJOfQTrxvKE2vn7hkjamigroGD5IaeRc ../data_2019_processed/student_DHO1K4jgiwZJOfQTrxvKE2vn7hkjamigroGD5IaeRc_transformed_smote.csv
10 - dQEFscjqnIlug8Tgq97JohhSQPG2DEOWJqS86wCrcY ../data_2019_processed/student_dQEFscjqnIlug8Tgq97JohhSQPG2DEOWJqS86wCrcY_transformed_smote.csv
11 - HFvs2CohmhHte+AaCzFasjzegGzxZKPhkrX23iI6Xo ../data_2019_processed/student_HFvs2CohmhHte+AaCzFasjzegGzxZKPhkrX23iI6Xo_transformed_smote.csv
12 - jgB9E8v3Z6PKdTRTCMAijBllA9YEMtrmHbe4qsbmJWw ../data_2019_processed/student_jgB9E8v3Z6PKdTRTCMAijBllA9YEMtrmHbe4qsbmJWw_transformed_smote.csv
13 - JkY++R7E8myldLN3on6iQ78Ee78zCbrLuggfwGju3I ../data_2019_processed/student_JkY++R7E8myldLN3on6iQ78Ee78zCbrLuggfwGju3I_transformed_smote.csv
14 - K4SLohf+TN1Ak8Dn8iE3Lme7rEMPISfppB2sXfHX8 ../data_2019_processed/student_K4SLohf+TN1Ak8Dn8iE3Lme7rEMPISfppB2sXfHX8_transformed_smote.csv
15 - oGaWetJJJEWHuvYdWYo826SQxfhCExVVQ2da8LE1Y7Q ../data_2019_processed/student_oGaWetJJJEWHuvYdWYo826SQxfhCExVVQ2da8LE1Y7Q_transformed_smote.csv
16 - pyt24oiDAHsmgWMvkFKz2fn2pwcHiXchd6KchLM ../data_2019_processed/student_pyt24oiDAHsmgWMvkFKz2fn2pwcHiXchd6KchLM_transformed_smote.csv
17 - QUNCATForxzK0HHw46LrGOMWh0eVA8Y5XWEiUXX+cQ ../data_2019_processed/student_QUNCATForxzK0HHw46LrGOMWh0eVA8Y5XWEiUXX+cQ_transformed_smote.csv
18 - rIl2UK9+bQ+tzpFdbJAdbBxEa5GbgrgC030yEaENLw ../data_2019_processed/student_rIl2UK9+bQ+tzpFdbJAdbBxEa5GbgrgC030yEaENLw_transformed_smote.csv
19 - RoBW3cDOO9wWRMPO2twQff83MPc+OXn6gJ+a1DafreI ../data_2019_processed/student_RoBW3cDOO9wWRMPO2twQff83MPc+OXn6gJ+a1DafreI_transformed_smote.csv
20 - SH3kQeyd5volraxw8vOyhlowNqWBPr1IJ9URNXUL4 ../data_2019_processed/student_SH3kQeyd5volraxw8vOyhlowNqWBPr1IJ9URNXUL4_transformed_smote.csv
21 - VVpwFNMrEglveh6MDN8lrRzTy5OwzglD4FURfM4A2is ../data_2019_processed/student_VVpwFNMrEglveh6MDN8lrRzTy5OwzglD4FURfM4A2is_transformed_smote.csv
22 - Wa1mcNmbh66S7VS6GIzyfCFMD3SGhbtDQyFP1ywJEsw ../data_2019_processed/student_Wa1mcNmbh66S7VS6GIzyfCFMD3SGhbtDQyFP1ywJEsw_transformed_smote.csv
23 - XCKRE0BWRHxfP1kZIihgtT+jUjSp2GE8v5ZlhcIhVmA ../data_2019_processed/student_XCKRE0BWRHxfP1kZIihgtT+jUjSp2GE8v5ZlhcIhVmA_transformed_smote.csv
24 - YI5Y79K6GXqAUoGP6PNyII8WKlAoel4urDxWSVVOvBw ../data_2019_processed/student_YI5Y79K6GXqAUoGP6PNyII8WKlAoel4urDxWSVVOvBw_transformed_smote.csv
25 - ypklj+8GJ15rOIH1lpKQtFJOuK+VdvyCuBPqhY3aoM ../data_2019_processed/student_ypklj+8GJ15rOIH1lpKQtFJOuK+VdvyCuBPqhY3aoM_transformed_smote.csv
26 - ZSsAZ0Pq+MCqFrnjsRFn5Ua09pMCVaOV9c8ZuYb7XQY ../data_2019_processed/student_ZSsAZ0Pq+MCqFrnjsRFn5Ua09pMCVaOV9c8ZuYb7XQY_transformed_smote.csv

In [5]:
# Exibe info
print(dataframe.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 542340 entries, 0 to 23751
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   activity            542340 non-null  float64
 1   location            542340 non-null  float64
 2   timestamp           542340 non-null  float64
 3   time_to_next_alarm  542340 non-null  float64
 4   sound               542340 non-null  float64
 5   proximity           542340 non-null  float64
 6   phone_lock          542340 non-null  float64
 7   light               542340 non-null  float64
 8   day_of_week         542340 non-null  float64
 9   minutes_day         542340 non-null  float64
 10  class               542340 non-null  object
dtypes: float64(10), object(1)
memory usage: 49.7+ MB
None

In [6]:
# convert data and show the new info
# activity
dataframe['activity'] = dataframe['activity'].replace(['Unknown'], '1')
dataframe['activity'] = dataframe['activity'].replace(['Still'], '2')
dataframe['activity'] = dataframe['activity'].replace(['Tilting'], '3')
dataframe['activity'] = dataframe['activity'].replace(['Exercise'], '4')
dataframe['activity'] = dataframe['activity'].replace(['In vehicle'], '5')
# class
dataframe['class'] = dataframe['class'].replace(['awake'], '0')
dataframe['class'] = dataframe['class'].replace(['asleep'], '1')
# day_of_week
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Tuesday'], '1')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Wednesday'], '2')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Thursday'], '3')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Friday'], '4')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Saturday'], '5')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Sunday'], '6')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Monday'], '7')
# phone_lock
dataframe['phone_lock'] = dataframe['phone_lock'].replace(['not locked'], '0')
dataframe['phone_lock'] = dataframe['phone_lock'].replace(['locked'], '1')
# location
dataframe['location'] = dataframe['location'].replace(['Other'], '1')
dataframe['location'] = dataframe['location'].replace(['University'], '2')
dataframe['location'] = dataframe['location'].replace(['House'], '3')

In [7]:
# timestamp
if 'timestamp2' in dataframe.columns:
    dataframe['timestamp_text'] = dataframe['timestamp']
    dataframe['timestamp'] = dataframe['timestamp2']
    del dataframe['timestamp2']
#dataframe['timestamp'] = datetime.strptime(dataframe['timestamp'],'%Y-%m-%d %H:%M:%S').timestamp() * 1000
#dataframe['timestamp'] = pd.to_datetime(dataframe['timestamp'],'%Y-%m-%d %H:%M:%S') * 1000
#dataframe['timestamp'] = dataframe['timestamp'].dt.second()
# activity
dataframe['activity'] = dataframe['activity'].astype(np.integer) 
dataframe['class'] = dataframe['class'].astype(np.integer) 
dataframe['day_of_week'] = dataframe['day_of_week'].astype(np.integer) 
dataframe['phone_lock'] = dataframe['phone_lock'].astype(np.integer) 
dataframe['location'] = dataframe['location'].astype(np.integer) 
# Exibe info
print(dataframe.info())# convert values

<class 'pandas.core.frame.DataFrame'>
Int64Index: 542340 entries, 0 to 23751
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   activity            542340 non-null  int64
 1   location            542340 non-null  int64
 2   timestamp           542340 non-null  float64
 3   time_to_next_alarm  542340 non-null  float64
 4   sound               542340 non-null  float64
 5   proximity           542340 non-null  float64
 6   phone_lock          542340 non-null  int64
 7   light               542340 non-null  float64
 8   day_of_week         542340 non-null  int64
 9   minutes_day         542340 non-null  float64
 10  class               542340 non-null  int64
dtypes: float64(6), int64(5)
memory usage: 49.7 MB
None

In [8]:
dataframe

,activity,location,timestamp,time_to_next_alarm,sound,proximity,phone_lock,light,day_of_week,minutes_day,class
0,0,0,0.000000e+00,0.982143,0.000000,1.0,0,0.000617,0,0.597637,0
1,0,0,0.000000e+00,0.982143,0.000000,1.0,0,0.000617,0,0.597637,0
2,0,0,3.211923e-07,0.982044,0.604408,1.0,0,0.000583,0,0.598332,0
3,0,0,3.211923e-07,0.982044,0.604408,1.0,0,0.005117,0,0.598332,0
4,0,0,3.211923e-07,0.981944,0.601849,1.0,0,0.000700,0,0.599027,0
...,...,...,...,...,...,...,...,...,...,...,...
23747,0,1,5.819100e-03,0.000099,0.000000,1.0,1,0.000236,0,0.510076,0
23748,0,1,5.819743e-03,0.000694,0.000000,1.0,1,0.000325,0,0.512856,0
23749,0,1,5.819743e-03,0.000595,0.000000,1.0,1,0.000325,0,0.513551,0
23750,0,1,5.820064e-03,0.000595,0.000000,1.0,1,0.000354,0,0.513551,0
23751,0,1,5.820064e-03,0.000496,0.000000,0.0,1,0.000000,0,0.514246,0

In [9]:
 #'pearson', "   "'spearman', 'kendall'
a = dataframe['class'].corr(dataframe['activity'])
b = dataframe['class'].corr(dataframe['location'])
#c = dataframe['class'].corr(dataframe['distanceHome'])
#d = dataframe['class'].corr(dataframe['showActuation'])
e = dataframe['class'].corr(dataframe['timestamp'])
f = dataframe['class'].corr(dataframe['day_of_week'])
g = dataframe['class'].corr(dataframe['light'])
h = dataframe['class'].corr(dataframe['phone_lock'])
i = dataframe['class'].corr(dataframe['proximity'])
j = dataframe['class'].corr(dataframe['sound'])
l = dataframe['class'].corr(dataframe['time_to_next_alarm'])
#m = dataframe['class'].corr(dataframe['sleep_time'])
#n = dataframe['class'].corr(dataframe['wakeup_time'])
p = dataframe['class'].corr(dataframe['minutes_day'])
o = dataframe['class'].corr(dataframe['class'])
print("Correlations")
corrrrrrr = (("activity",a),
            ("location",b),
      #      ("distanceHome",c),
     #       ("showActuation",d),
            ("timestamp",e),
            ("day_of_week",f),
            ("light",g),
            ("phone_lock",h),
            ("proximity",i),
            ("sound",j),
#            ("sleep_time",m),
#            ("wakeup_time",n),
            ("time_to_next_alarm",l),
            ("minutes_day",p),
            ("class",o))
print (corrrrrrr)

Correlations
(('activity', -0.049665916611361806), ('location', 0.14964496377212141), ('timestamp', -0.03698786320498404), ('day_of_week', 0.014935275332598936), ('light', -0.01711961330128372), ('phone_lock', 0.13043323164724085), ('proximity', -0.05867197105413972), ('sound', 0.1470811247586273), ('time_to_next_alarm', -0.18661228305150912), ('minutes_day', -0.15395497692332927), ('class', 1.0))

In [10]:
type(corrrrrrr)

tuple

In [11]:
tests = pd.DataFrame(corrrrrrr,columns=("Feature","Correlation"))
tests.sort_values(by=['Correlation'])

               Feature  Correlation
8   time_to_next_alarm    -0.186612
9          minutes_day    -0.153955
6            proximity    -0.058672
0             activity    -0.049666
2            timestamp    -0.036988
4                light    -0.017120
3          day_of_week     0.014935
5           phone_lock     0.130433
7                sound     0.147081
1             location     0.149645
10               class     1.000000

# Only training correlation

In [12]:
outputFolders = "train/"

In [13]:
dataframe = loadDataFromFolders(trainFolders,mainfolder,file_name_modifier)
#dataframe = pd.read_csv("dados2019/student_a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4.csv", delimiter=',', encoding="utf8")

19 datasets
0 - 0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs ../data_2019_processed/student_0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs_transformed_smote.csv
1 - 0tdmm6rwW3KquQ73ATYYJ5JkpMtvbppJ0VzA2GExdA ../data_2019_processed/student_0tdmm6rwW3KquQ73ATYYJ5JkpMtvbppJ0VzA2GExdA_transformed_smote.csv
2 - 2cyV53lVyUtlMj0BRwilEWtYJwUiviYoL48cZBPBq0 ../data_2019_processed/student_2cyV53lVyUtlMj0BRwilEWtYJwUiviYoL48cZBPBq0_transformed_smote.csv
3 - 2J22RukYnEbKTk7t+iUVDBkorcyL5NKN6TrLe89ys ../data_2019_processed/student_2J22RukYnEbKTk7t+iUVDBkorcyL5NKN6TrLe89ys_transformed_smote.csv
4 - 7EYF5I04EVqisUJCVNHlqn77UAuOmwL2Dahxd3cA ../data_2019_processed/student_7EYF5I04EVqisUJCVNHlqn77UAuOmwL2Dahxd3cA_transformed_smote.csv
5 - a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4 ../data_2019_processed/student_a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4_transformed_smote.csv
6 - ae4JJBZDycEcY8McJF+3BxyvZ1619y03BNdCxzpZTc ../data_2019_processed/student_ae4JJBZDycEcY8McJF+3BxyvZ1619y03BNdCxzpZTc_transformed_smote.csv
7 - Ch3u5Oaz96VSrQbf0z31X6jEIbeIekkC0mwPzCdeJ1U ../data_2019_processed/student_Ch3u5Oaz96VSrQbf0z31X6jEIbeIekkC0mwPzCdeJ1U_transformed_smote.csv
8 - CH8f0yZkZL13zWuE9ks1CkVJRVrr+jsGdUXHrZ6YeA ../data_2019_processed/student_CH8f0yZkZL13zWuE9ks1CkVJRVrr+jsGdUXHrZ6YeA_transformed_smote.csv
9 - DHO1K4jgiwZJOfQTrxvKE2vn7hkjamigroGD5IaeRc ../data_2019_processed/student_DHO1K4jgiwZJOfQTrxvKE2vn7hkjamigroGD5IaeRc_transformed_smote.csv
10 - dQEFscjqnIlug8Tgq97JohhSQPG2DEOWJqS86wCrcY ../data_2019_processed/student_dQEFscjqnIlug8Tgq97JohhSQPG2DEOWJqS86wCrcY_transformed_smote.csv
11 - HFvs2CohmhHte+AaCzFasjzegGzxZKPhkrX23iI6Xo ../data_2019_processed/student_HFvs2CohmhHte+AaCzFasjzegGzxZKPhkrX23iI6Xo_transformed_smote.csv
12 - jgB9E8v3Z6PKdTRTCMAijBllA9YEMtrmHbe4qsbmJWw ../data_2019_processed/student_jgB9E8v3Z6PKdTRTCMAijBllA9YEMtrmHbe4qsbmJWw_transformed_smote.csv
13 - JkY++R7E8myldLN3on6iQ78Ee78zCbrLuggfwGju3I ../data_2019_processed/student_JkY++R7E8myldLN3on6iQ78Ee78zCbrLuggfwGju3I_transformed_smote.csv
14 - K4SLohf+TN1Ak8Dn8iE3Lme7rEMPISfppB2sXfHX8 ../data_2019_processed/student_K4SLohf+TN1Ak8Dn8iE3Lme7rEMPISfppB2sXfHX8_transformed_smote.csv
15 - oGaWetJJJEWHuvYdWYo826SQxfhCExVVQ2da8LE1Y7Q ../data_2019_processed/student_oGaWetJJJEWHuvYdWYo826SQxfhCExVVQ2da8LE1Y7Q_transformed_smote.csv
16 - pyt24oiDAHsmgWMvkFKz2fn2pwcHiXchd6KchLM ../data_2019_processed/student_pyt24oiDAHsmgWMvkFKz2fn2pwcHiXchd6KchLM_transformed_smote.csv
17 - QUNCATForxzK0HHw46LrGOMWh0eVA8Y5XWEiUXX+cQ ../data_2019_processed/student_QUNCATForxzK0HHw46LrGOMWh0eVA8Y5XWEiUXX+cQ_transformed_smote.csv
18 - SH3kQeyd5volraxw8vOyhlowNqWBPr1IJ9URNXUL4 ../data_2019_processed/student_SH3kQeyd5volraxw8vOyhlowNqWBPr1IJ9URNXUL4_transformed_smote.csv

In [14]:
# convert data and show the new info
# activity
dataframe['activity'] = dataframe['activity'].replace(['Unknown'], '1')
dataframe['activity'] = dataframe['activity'].replace(['Still'], '2')
dataframe['activity'] = dataframe['activity'].replace(['Tilting'], '3')
dataframe['activity'] = dataframe['activity'].replace(['Exercise'], '4')
dataframe['activity'] = dataframe['activity'].replace(['In vehicle'], '5')
# class
dataframe['class'] = dataframe['class'].replace(['awake'], '0')
dataframe['class'] = dataframe['class'].replace(['asleep'], '1')
# day_of_week
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Tuesday'], '1')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Wednesday'], '2')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Thursday'], '3')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Friday'], '4')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Saturday'], '5')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Sunday'], '6')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Monday'], '7')
# phone_lock
dataframe['phone_lock'] = dataframe['phone_lock'].replace(['not locked'], '0')
dataframe['phone_lock'] = dataframe['phone_lock'].replace(['locked'], '1')
# location
dataframe['location'] = dataframe['location'].replace(['Other'], '1')
dataframe['location'] = dataframe['location'].replace(['University'], '2')
dataframe['location'] = dataframe['location'].replace(['House'], '3')

In [15]:
# timestamp
if 'timestamp2' in dataframe.columns:
    dataframe['timestamp_text'] = dataframe['timestamp']
    dataframe['timestamp'] = dataframe['timestamp2']
    del dataframe['timestamp2']
#dataframe['timestamp'] = datetime.strptime(dataframe['timestamp'],'%Y-%m-%d %H:%M:%S').timestamp() * 1000
#dataframe['timestamp'] = pd.to_datetime(dataframe['timestamp'],'%Y-%m-%d %H:%M:%S') * 1000
#dataframe['timestamp'] = dataframe['timestamp'].dt.second()
# activity
dataframe['activity'] = dataframe['activity'].astype(np.integer) 
dataframe['class'] = dataframe['class'].astype(np.integer) 
dataframe['day_of_week'] = dataframe['day_of_week'].astype(np.integer) 
dataframe['phone_lock'] = dataframe['phone_lock'].astype(np.integer) 
dataframe['location'] = dataframe['location'].astype(np.integer) 
# Exibe info
print(dataframe.info())# convert values

<class 'pandas.core.frame.DataFrame'>
Int64Index: 407452 entries, 0 to 12708
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   activity            407452 non-null  int64
 1   location            407452 non-null  int64
 2   timestamp           407452 non-null  float64
 3   time_to_next_alarm  407452 non-null  float64
 4   sound               407452 non-null  float64
 5   proximity           407452 non-null  float64
 6   phone_lock          407452 non-null  int64
 7   light               407452 non-null  float64
 8   day_of_week         407452 non-null  int64
 9   minutes_day         407452 non-null  float64
 10  class               407452 non-null  int64
dtypes: float64(6), int64(5)
memory usage: 37.3 MB
None

In [16]:
 #'pearson', "   "'spearman', 'kendall'
a = dataframe['class'].corr(dataframe['activity'])
b = dataframe['class'].corr(dataframe['location'])
#c = dataframe['class'].corr(dataframe['distanceHome'])
#d = dataframe['class'].corr(dataframe['showActuation'])
#e = dataframe['class'].corr(dataframe['timestamp'])
f = dataframe['class'].corr(dataframe['day_of_week'])
g = dataframe['class'].corr(dataframe['light'])
h = dataframe['class'].corr(dataframe['phone_lock'])
i = dataframe['class'].corr(dataframe['proximity'])
j = dataframe['class'].corr(dataframe['sound'])
l = dataframe['class'].corr(dataframe['time_to_next_alarm'])
#m = dataframe['class'].corr(dataframe['sleep_time'])
#n = dataframe['class'].corr(dataframe['wakeup_time'])
p = dataframe['class'].corr(dataframe['minutes_day'])
o = dataframe['class'].corr(dataframe['class'])
print("Correlations")
corrrrrrr = (("activity",a),
            ("location",b),
           # ("distanceHome",c),
           # ("showActuation",d),
           # ("timestamp",e),
            ("day_of_week",f),
            ("light",g),
            ("phone_lock",h),
            ("proximity",i),
            ("sound",j),
#            ("sleep_time",m),
#            ("wakeup_time",n),
            ("time_to_next_alarm",l),
            ("minutes_day",p),
            ("class",o))
print (corrrrrrr)

Correlations
(('activity', -0.04623200205491705), ('location', 0.13264131298545426), ('day_of_week', 0.03233443521863478), ('light', -0.019724882419779245), ('phone_lock', 0.1194282259522165), ('proximity', -0.09231796858979208), ('sound', 0.1607963477499231), ('time_to_next_alarm', -0.1881210519246663), ('minutes_day', -0.1341328596354178), ('class', 1.0))

In [17]:
tests = pd.DataFrame(corrrrrrr,columns=("Feature","Correlation"))
tests.sort_values(by=['Correlation'])

              Feature  Correlation
7  time_to_next_alarm    -0.188121
8         minutes_day    -0.134133
5           proximity    -0.092318
0            activity    -0.046232
3               light    -0.019725
2         day_of_week     0.032334
4          phone_lock     0.119428
1            location     0.132641
6               sound     0.160796
9               class     1.000000

# Test Folder

In [18]:
dataframe = loadDataFromFolders(testFolders,mainfolder,file_name_modifier)
#dataframe = pd.read_csv("dados2019/student_a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4.csv", delimiter=',', encoding="utf8")

8 datasets
0 - rIl2UK9+bQ+tzpFdbJAdbBxEa5GbgrgC030yEaENLw ../data_2019_processed/student_rIl2UK9+bQ+tzpFdbJAdbBxEa5GbgrgC030yEaENLw_transformed_smote.csv
1 - RoBW3cDOO9wWRMPO2twQff83MPc+OXn6gJ+a1DafreI ../data_2019_processed/student_RoBW3cDOO9wWRMPO2twQff83MPc+OXn6gJ+a1DafreI_transformed_smote.csv
2 - VVpwFNMrEglveh6MDN8lrRzTy5OwzglD4FURfM4A2is ../data_2019_processed/student_VVpwFNMrEglveh6MDN8lrRzTy5OwzglD4FURfM4A2is_transformed_smote.csv
3 - Wa1mcNmbh66S7VS6GIzyfCFMD3SGhbtDQyFP1ywJEsw ../data_2019_processed/student_Wa1mcNmbh66S7VS6GIzyfCFMD3SGhbtDQyFP1ywJEsw_transformed_smote.csv
4 - XCKRE0BWRHxfP1kZIihgtT+jUjSp2GE8v5ZlhcIhVmA ../data_2019_processed/student_XCKRE0BWRHxfP1kZIihgtT+jUjSp2GE8v5ZlhcIhVmA_transformed_smote.csv
5 - YI5Y79K6GXqAUoGP6PNyII8WKlAoel4urDxWSVVOvBw ../data_2019_processed/student_YI5Y79K6GXqAUoGP6PNyII8WKlAoel4urDxWSVVOvBw_transformed_smote.csv
6 - ypklj+8GJ15rOIH1lpKQtFJOuK+VdvyCuBPqhY3aoM ../data_2019_processed/student_ypklj+8GJ15rOIH1lpKQtFJOuK+VdvyCuBPqhY3aoM_transformed_smote.csv
7 - ZSsAZ0Pq+MCqFrnjsRFn5Ua09pMCVaOV9c8ZuYb7XQY ../data_2019_processed/student_ZSsAZ0Pq+MCqFrnjsRFn5Ua09pMCVaOV9c8ZuYb7XQY_transformed_smote.csv

In [19]:
# convert data and show the new info
# activity
dataframe['activity'] = dataframe['activity'].replace(['Unknown'], '1')
dataframe['activity'] = dataframe['activity'].replace(['Still'], '2')
dataframe['activity'] = dataframe['activity'].replace(['Tilting'], '3')
dataframe['activity'] = dataframe['activity'].replace(['Exercise'], '4')
dataframe['activity'] = dataframe['activity'].replace(['In vehicle'], '5')
# class
dataframe['class'] = dataframe['class'].replace(['awake'], '0')
dataframe['class'] = dataframe['class'].replace(['asleep'], '1')
# day_of_week
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Tuesday'], '1')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Wednesday'], '2')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Thursday'], '3')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Friday'], '4')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Saturday'], '5')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Sunday'], '6')
dataframe['day_of_week'] = dataframe['day_of_week'].replace(['Monday'], '7')
# phone_lock
dataframe['phone_lock'] = dataframe['phone_lock'].replace(['not locked'], '0')
dataframe['phone_lock'] = dataframe['phone_lock'].replace(['locked'], '1')
# location
dataframe['location'] = dataframe['location'].replace(['Other'], '1')
dataframe['location'] = dataframe['location'].replace(['University'], '2')
dataframe['location'] = dataframe['location'].replace(['House'], '3')

In [20]:
# timestamp
if 'timestamp2' in dataframe.columns:
    dataframe['timestamp_text'] = dataframe['timestamp']
    dataframe['timestamp'] = dataframe['timestamp2']
    del dataframe['timestamp2']
#dataframe['timestamp'] = datetime.strptime(dataframe['timestamp'],'%Y-%m-%d %H:%M:%S').timestamp() * 1000
#dataframe['timestamp'] = pd.to_datetime(dataframe['timestamp'],'%Y-%m-%d %H:%M:%S') * 1000
#dataframe['timestamp'] = dataframe['timestamp'].dt.second()
# activity
dataframe['activity'] = dataframe['activity'].astype(np.integer) 
dataframe['class'] = dataframe['class'].astype(np.integer) 
dataframe['day_of_week'] = dataframe['day_of_week'].astype(np.integer) 
dataframe['phone_lock'] = dataframe['phone_lock'].astype(np.integer) 
dataframe['location'] = dataframe['location'].astype(np.integer) 
# Exibe info
print(dataframe.info())# convert values

<class 'pandas.core.frame.DataFrame'>
Int64Index: 134888 entries, 0 to 23751
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   activity            134888 non-null  int64
 1   location            134888 non-null  int64
 2   timestamp           134888 non-null  float64
 3   time_to_next_alarm  134888 non-null  float64
 4   sound               134888 non-null  float64
 5   proximity           134888 non-null  float64
 6   phone_lock          134888 non-null  int64
 7   light               134888 non-null  float64
 8   day_of_week         134888 non-null  int64
 9   minutes_day         134888 non-null  float64
 10  class               134888 non-null  int64
dtypes: float64(6), int64(5)
memory usage: 12.3 MB
None

In [21]:
#'pearson', "   "'spearman', 'kendall'
a = dataframe['class'].corr(dataframe['activity'])
b = dataframe['class'].corr(dataframe['location'])
#c = dataframe['class'].corr(dataframe['distanceHome'])
#d = dataframe['class'].corr(dataframe['showActuation'])
#e = dataframe['class'].corr(dataframe['timestamp'])
f = dataframe['class'].corr(dataframe['day_of_week'])
g = dataframe['class'].corr(dataframe['light'])
h = dataframe['class'].corr(dataframe['phone_lock'])
i = dataframe['class'].corr(dataframe['proximity'])
j = dataframe['class'].corr(dataframe['sound'])
l = dataframe['class'].corr(dataframe['time_to_next_alarm'])
#m = dataframe['class'].corr(dataframe['sleep_time'])
#n = dataframe['class'].corr(dataframe['wakeup_time'])
p = dataframe['class'].corr(dataframe['minutes_day'])
o = dataframe['class'].corr(dataframe['class'])
print("Correlations")
corrrrrrr = (("activity",a),
            ("location",b),
           # ("distanceHome",c),
           # ("showActuation",d),
           # ("timestamp",e),
            ("day_of_week",f),
            ("light",g),
            ("phone_lock",h),
            ("proximity",i),
            ("sound",j),
#            ("sleep_time",m),
#            ("wakeup_time",n),
            ("time_to_next_alarm",l),
            ("minutes_day",p),
            ("class",o))
print (corrrrrrr)

Correlations
(('activity', -0.06012253719239137), ('location', 0.2002470885794131), ('day_of_week', -0.036075040247058744), ('light', -0.011138030766290536), ('phone_lock', 0.1641532544251263), ('proximity', 0.04394069928722668), ('sound', 0.14409989614797697), ('time_to_next_alarm', -0.1818090266026317), ('minutes_day', -0.21527085123623185), ('class', 0.9999999999999999))

In [22]:
tests = pd.DataFrame(corrrrrrr,columns=("Feature","Correlation"))
tests.sort_values(by=['Correlation'])

              Feature  Correlation
8         minutes_day    -0.215271
7  time_to_next_alarm    -0.181809
0            activity    -0.060123
2         day_of_week    -0.036075
3               light    -0.011138
5           proximity     0.043941
6               sound     0.144100
4          phone_lock     0.164153
1            location     0.200247
9               class     1.000000